---
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "mobilecoinfoundation/coredev"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "mobilecoinfoundation/coredev"
    ignore:
      # See https://github.com/dtolnay/rust-toolchain/issues/45 tags aren't used
      # by rust-toolchain. Using a branch name will cause dependabot to suggest
      # which ever branch happens to be the newest
      - dependency-name: "rust-toolchain"
