targets = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-DFS-2016",
    "GPL-3.0",
    "LGPL-3.0",
]
deny = []
copyleft = "allow"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "deny"
highlight = "all"
allow = []
deny = [
    # https://github.com/briansmith/ring/issues/774
    { name = "ring" },
]
skip = [
    # Workaround for path only dependencies,
    # https://github.com/EmbarkStudios/cargo-deny/issues/241
    # { name = "some/dev/only/path" },
]
skip-tree = [ ]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
