[package]
name = "test-helper"
version = "2.0.0"
authors = ["Chris Beck <beck.ct@gmail.com>"]
edition = "2018"

[dependencies]
rand_core = { version = "0.6", default-features = false }
rand_hc = "0.3"
