---
name: pr

"on":
  pull_request:

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          github-token: "${{ secrets.MEOWBLECOIN_PAT }}"
          project-url: https://github.com/orgs/mobilecoinfoundation/projects/7
      - uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORED: "Cargo.lock"
          INPUT_SIZES: >
            {
              "0": "XS",
              "30": "S",
              "100": "M",
              "250": "L",
              "500": "XL",
              "1000": "XXL",
              "1500": "OHLAWDHECOMIN"
            }
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
